extends: e2e_train_position_velocity_error.yaml

environment:
  position_perturbation: 0.0
  attitude_perturbation_deg: 0.0
  initial_pose_randomization: null

evaluation:
  deterministic: true
  seed_start: 42

mission:
  type: hover
  force_floor_start: false

experiment:
  condition: position-velocity-error-evaluation
