extends: view_payload_history_integral_v1_nominal.yaml
environment:
  payload:
    mass: 0.010
    offset: [0.021213203435596427, 0.021213203435596423]
experiment:
  condition: view-history-integral-payload-10g-r30mm-az045
