extends: view_payload_history_integral_v1_nominal.yaml
environment:
  payload:
    mass: 0.010
    offset: [0.02121320343559642, -0.02121320343559643]
experiment:
  condition: view-history-integral-payload-10g-r30mm-az315
